name: GitHub Actions Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run a Simple Script
        run: |
          echo "Hello Vaishali! Your fresh GitHub Actions Pipeline is working perfectly."
          echo "Current date and time:"
          date
